### ISSUE TITLE
Version `1.18.0` fails with `AttributeError: module 'pulumi.runtime.proto' has no attribute 'PolicySeverity'`

### ISSUE THREAD

**Issue by arnaubt** [pulumi/pulumi-policy#416]
### What happened?

Previews and ups fail with the following error:

```
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.11/site-packages/pulumi/policy/__main__.py", line 59, in main
    runpy.run_path(program, run_name="__main__")
  File "<frozen runpy>", line 308, in run_path
  File "<frozen runpy>", line 88, in _run_code
  File "/root/project/policy-repo/policies/policy_pack/__main__.py", line 13, in <module>
    from pulumi_policy import (
  File "/tmp/venv/lib/python3.11/site-packages/pulumi_policy/__init__.py", line 20, in <module>
    from .policy import (
  File "/tmp/venv/lib/python3.11/site-packages/pulumi_policy/policy.py", line 934, in <module>
    class _PolicyAnalyzerServicer(proto.AnalyzerServicer):
  File "/tmp/venv/lib/python3.11/site-packages/pulumi_policy/policy.py", line 1356, in _PolicyAnalyzerServicer
    def _map_severity(self, severity: Optional[Severity] = None) -> proto.PolicySeverity.ValueType:
                                                                    ^^^^^^^^^^^^^^^^^^^^

AttributeError: module 'pulumi.runtime.proto' has no attribute 'PolicySeverity'
```

We were able to fix it by reverting to `1.17.0`. Looks like it was introduced in https://github.com/pulumi/pulumi-policy/pull/410

### Example

We've seen the error on different Python-based projects.

### Output of `pulumi about`

Pulumi CLI: `3.131.0`
Pulumi Python: `3.187.0`
pulumi-policy: `1.18.0`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The fix shipped with pulumi-policy 1.18.1.
